"""CamillaDSP YAML snippet generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping


def yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def generate_camilladsp_yaml(
    num_outputs: int,
    num_inputs: int,
    filter_paths: Mapping[tuple[int, int], Mapping[str, Path]],
    output_dir: Path,
    config: Mapping[str, Any],
) -> str:
    prefix = str(config.get("camilladsp_filter_path_prefix", ""))
    use_absolute = bool(config.get("camilladsp_absolute_paths", False))
    conv_type = str(config.get("camilladsp_conv_type", "wav")).lower()
    if conv_type not in {"wav", "raw"}:
        raise ValueError("camilladsp_conv_type must be 'wav' or 'raw'.")
    path_key = "wav" if conv_type == "wav" else "txt"
    branch_count = num_outputs * num_inputs

    def filter_filename(output_channel: int, input_channel: int) -> str:
        item = filter_paths[(output_channel, input_channel)]
        path = item.get(path_key)
        if path is None:
            needed = "'wav'" if path_key == "wav" else "'txt'"
            raise ValueError(
                f"CamillaDSP YAML generation with camilladsp_conv_type={conv_type!r} "
                f"requires {needed} FIR files. Set output_format to {needed} or 'both'."
            )
        if use_absolute:
            return str(path.resolve())
        if prefix:
            return str(Path(prefix) / path.name)
        try:
            return str(path.relative_to(output_dir))
        except ValueError:
            return path.name

    lines: list[str] = []
    lines.append("# CamillaDSP FIR matrix snippet generated by OptiMIMO")
    lines.append("# Pipeline topology: input channels -> N*N FIR branches -> summed speaker outputs")
    lines.append("filters:")
    for output_channel in range(num_outputs):
        for input_channel in range(num_inputs):
            name = f"fir_o{output_channel:02d}_i{input_channel:02d}"
            lines.append(f"  {name}:")
            lines.append("    type: Conv")
            lines.append("    parameters:")
            if conv_type == "wav":
                lines.append("      type: Wav")
                lines.append(f"      filename: {yaml_quote(filter_filename(output_channel, input_channel))}")
            else:
                lines.append("      type: Raw")
                lines.append(f"      filename: {yaml_quote(filter_filename(output_channel, input_channel))}")
                lines.append("      format: TEXT")

    lines.append("mixers:")
    lines.append("  fir_matrix_expand:")
    lines.append("    channels:")
    lines.append(f"      in: {num_inputs}")
    lines.append(f"      out: {branch_count}")
    lines.append("    mapping:")
    for output_channel in range(num_outputs):
        for input_channel in range(num_inputs):
            branch = output_channel * num_inputs + input_channel
            lines.append(f"      - dest: {branch}")
            lines.append("        sources:")
            lines.append(f"          - channel: {input_channel}")
            lines.append("            gain: 0.0")
            lines.append("            inverted: false")

    lines.append("  fir_matrix_sum:")
    lines.append("    channels:")
    lines.append(f"      in: {branch_count}")
    lines.append(f"      out: {num_outputs}")
    lines.append("    mapping:")
    for output_channel in range(num_outputs):
        lines.append(f"      - dest: {output_channel}")
        lines.append("        sources:")
        for input_channel in range(num_inputs):
            branch = output_channel * num_inputs + input_channel
            lines.append(f"          - channel: {branch}")
            lines.append("            gain: 0.0")
            lines.append("            inverted: false")

    lines.append("pipeline:")
    lines.append("  - type: Mixer")
    lines.append("    name: fir_matrix_expand")
    for output_channel in range(num_outputs):
        for input_channel in range(num_inputs):
            branch = output_channel * num_inputs + input_channel
            name = f"fir_o{output_channel:02d}_i{input_channel:02d}"
            lines.append("  - type: Filter")
            lines.append(f"    channels: [{branch}]")
            lines.append("    names:")
            lines.append(f"      - {name}")
    lines.append("  - type: Mixer")
    lines.append("    name: fir_matrix_sum")
    lines.append("")
    return "\n".join(lines)
